### ISSUE TITLE
Search misses bugs

### ISSUE THREAD

**Issue by bgilbert** [openshift/ci-search#92]
Search sometimes misses open bugs, even when the search string is the exact title of the bug.  Examples:
- [Search](https://search.ci.openshift.org/?maxAge=168h&context=1&type=bug%2Bjunit&name=4.4&maxMatches=5&maxBytes=20971520&groupBy=job&search=Application+behind+service+load+balancer+with+PDB+is+not+disrupted), [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1868489)
- [Search](https://search.ci.openshift.org/?maxAge=168h&context=1&type=bug%2Bjunit&name=4.6&maxMatches=5&maxBytes=20971520&groupBy=job&search=%5C%5Bsig-api-machinery%5C%5D%5C%5BFeature%3AAPIServer%5C%5D%5C%5BLate%5C%5D+kubelet+terminates+kube-apiserver+gracefully), [bug 1](https://bugzilla.redhat.com/show_bug.cgi?id=1882750), [bug 2](https://bugzilla.redhat.com/show_bug.cgi?id=1886563), [alternative search](https://search.ci.openshift.org/?search=kubelet+terminates+kube-apiserver+gracefully&maxAge=168h&context=1&type=bug%2Bjunit&name=4.6&maxMatches=5&maxBytes=20971520&groupBy=job).

I've also seen this happen on certain searches and then correct itself later.

This makes search much less useful, since I still need to search Bugzilla directly before reporting a new issue.

**Comment by bparees** [comment]
in your first search, the issue is that you had a "job name" value specified (`name=4.4` in the query params).  That shouldn't interfere w/ bug searches, but it seems like it did in this case?

this search is working:
https://search.ci.openshift.org/?search=Application+behind+service+load+balancer+with+PDB+is+not+disrupted&maxAge=168h&context=1&type=bug&name=&maxMatches=5&maxBytes=20971520&groupBy=job

while your search still is not:
https://search.ci.openshift.org/?maxAge=168h&context=1&type=bug%2Bjunit&name=4.4&maxMatches=5&maxBytes=20971520&groupBy=job&search=Application+behind+service+load+balancer+with+PDB+is+not+disrupted

i think the same issue applies to your second search.

it would be good to figure out why ci-search's bug search isn't just ignoring the job name field when doing bug searches, though.

**Comment by bgilbert** [comment]
Those query URLs came from Sippy links, FWIW.

**Comment by bparees** [comment]
> Those query URLs came from Sippy links, FWIW.

i assume you're talking about these links:

![image](https://user-images.githubusercontent.com/4974046/95517335-c9c3f200-098e-11eb-90bf-dd42d51b968a.png)

(specifically the test name link).

The intent of those links is to show you the jobs where the test failed, not the bugs(which is why it filters it by job name, so it's only showing you results from jobs related to the release you were looking at).  

We can fix sippy to make that explicit by changing the type to "junit" instead of "junit+bug" in the query url.  But if we can fix the ci-search issue so that you also get BZ results, even w/ a job name specified, that is probably the better solution.

**Comment by bgilbert** [comment]
The test name links, yeah.  The "junit+bug" menu entry did reinforce the idea that I should expect to see bugs.  Also, the build-watcher docs say:

> It is good practice to always click on the Test Name first and check to see if a BZ has recently been opened for that test and just hasn’t shown up in Sippy yet

Either fix SGTM.

**Comment by bparees** [comment]
fixing the search results in #93, adding the "related BZ results"(i.e. BZs that matched the test name but are targeted to a different release) to sippy will be a bigger effort.
